[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "risk-engine"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "lseg-data",
]

[tool.setuptools]
packages = ["risk_engine"]